# Site Settings
title: Tiago Santos | Software Architect
url: 'https://tvcsantos.github.io'
description: Tiago Santos' Résumé
author: Tiago Santos
keywords: "software architect, backend developer, kotlin, java, spring, aws, resume"

# Theme
theme_skin: ceramic # blue turquoise green berry orange ceramic

# Plugins
plugins:
  - jekyll-sitemap

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true
  silence_deprecations:
    - import
    - global-builtin

encoding: "utf-8"

# Exclude from build
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - Makefile
  - LICENSE

# Development Settings
port: 4000
host: 0.0.0.0
